module.exports = {
    "T-CORRECT-0001": "Helyes!",
    "T-CORRECT-0002": "Remek, minden feladatot megoldottál, mehetünk tovább.",
    "T-INCORRECT-0001": "Sajnos ez nem a helyes válasz, próbálkozz egy másikkal.",
    "T-INCORRECT-0002": "Hmm, úgy néz ki még nem végeztél minden feladattal, próbáld meg megoldani mindet.",
    "T-ERROR-CODE-0000": "Hoppá! A feladat ellenőrzése nem sikerült egy belső hiba miatt. Kérlek próbáld meg elküldeni még egyszer. Ha a probléma tartósan fennáll, vedd fel velünk a kapcsolatot #Slack-en vagy a hello@codeberryschool.com email címen. Hiba: E0000 - validator function exception.",
    "T-ERROR-CODE-0001": "Hoppá! A feladat ellenőrzése nem sikerült egy belső hiba miatt. Kérlek próbáld meg elküldeni még egyszer. Ha a probléma tartósan fennáll, vedd fel velünk a kapcsolatot #Slack-en vagy a hello@codeberryschool.com email címen. Hiba: E0001 - url doesn't exist.",
    "T-ERROR-CODE-0002": "Hoppá! A feladat ellenőrzése nem sikerült egy belső hiba miatt. Kérlek próbáld meg elküldeni még egyszer. Ha a probléma tartósan fennáll, vedd fel velünk a kapcsolatot #Slack-en vagy a hello@codeberryschool.com email címen. Hiba: E0002 - promise timed out after %s seconds.",
    "T-ERROR-CODE-0003": "Hoppá! A feladat ellenőrzése nem sikerült egy belső hiba miatt. Kérlek próbáld meg elküldeni még egyszer. Ha a probléma tartósan fennáll, vedd fel velünk a kapcsolatot #Slack-en vagy a hello@codeberryschool.com email címen. Hiba: E0003 - html parser error.",
    "T0000": "A megadott gitHub felhasználónévvel nem létezik profil (%s).",
    "T0001": "Szuper, megtaláltuk a gitHub profilodat: %s. Mehetünk tovább.",
    "T0002": "A háttérszínt sikeresen beállítottad.",
    "T0003": "Állítsd be a háttérszínt.",
    "T0004": "A body background-property értékét kell módosítanod.",
    "T0006": "Nem ez a tag az.",
    "T0007": "A legelső címsor HTML tag-jére gondoltunk.",
    "T0008": "Hozd létre a képet.",
    "T0009": "Nem találtunk az oldalon a <body> tag-en belül <img> tag-et.",
    "T0010": "Hozd létre a képaláírást.",
    "T0011": "Nem találtunk az oldalon a <body> tag-en belül <figcaption> tag-et.",
    "T0012": "Hozd létre a kép keretét.",
    "T0013": "Nem találtunk az oldalon a <body> tag-en belül <figure> tag-et.",
    "T0014": "Csomagold be a képet és a képaláírást egy szemantikusan helyes HTML tag-be.",
    "T0015": "Nem találtunk az oldalon a <figure> tag-en belül <img> és <figcaption> tag-et.",
    "T0016": "Másold be a három bekezdést.",
    "T0017": "Nem találtunk az oldalon a <body> tag-en belül három <p> tag-et.",
    "T0018": "Hozd létre a bekezdések keretét.",
    "T0019": "Nem találtunk az oldalon a <body> tag-en belül <article> tag-et.",
    "T0020": "Csomagold be a három bekezdést egy szemantikusan helyes HTML tag-be.",
    "T0021": "Nem találtunk az oldalon az <article> tag-en belül három <p> tag-et.",
    "T0023": "Egy kék szín rgba kódjára vagyunk kíváncsiak",
    "T0024": "Egy szürke szín rgba kódja például: rgba(1, 1, 1, 0.5)",
    "T0025": "A megoldás egy írásjel.",
    "T0026": "A százalékos értéket várjuk megoldásként.",
    "T0027": "A CSS property nevét várjuk megoldásként.",
    "T0028": "A CSS property nevét várjuk megoldásként.",
    "T0029": "Hasonlít az a:hover-hez, csak a legfontosabb címsorra.",
    "T0030": "Szuper, ez egy valós JSBin url.",
    "T0031": "Kérlek, valós JSBin url-t adj meg (pl.: http://jsbin.com/holab vagy output.jsbin.com/holab)",
};